--- # ---------------------------------- Global Configs -----------------------------------
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "elasticsearch-rules.yaml"
  - "kafka-rules.yaml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
## Add in site