global:
  resolve_timeout: 1m
  
route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: monitoring2204@gmail.com
    from: monitoring2204@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: monitoring2204@gmail.com
    auth_identity: monitoring2204@gmail.com
    auth_password: rglqpioinpxcloyi
    send_resolved: true