global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'monitoring2204@gmail.com'
    from: 'monitoring2204@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'monitoring2204@gmail.com'
    auth_identity: 'monitoring2204@gmail.com'
    auth_password: 'esewetptcmvpkcnr'