--- # ---------------------------------- Global Configs -----------------------------------
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "elasticsearch-rules.yml"
  - "kafka-rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  # ---------------------------------- Node Exporter -----------------------------------
  - job_name: "node-exporter"
    static_configs:
      - targets: ["nodeexporter:9100"]
        labels:
          group: "self"

      - targets: ["10.90.25.239:9100", "10.90.25.240:9100", "10.90.25.242:9100"]
        labels:
          group: "elasticsearch"

      # - targets: ["kafka01:9100", "kafka02:9100", "kafka03:9100"]
      #   labels:
      #     group: "kafka"

      # - targets: ["logstash01:9100", "logstash02:9100", "logstash03:9100"]
      #   labels:
      #     group: "logstash"

      # - targets: ["grafana.tiptool.co:9100"]
      #   labels:
      #     group: "grafana"

      # - targets: ["kibana:9100"]
      #   labels:
      #     group: "kibana"

      # - targets: ["logger:9100"]
      #   labels:
      #     group: "logger"

      # - targets: ["gitlab:9100"]
      #   labels:
      #     group: "gitlab"

  # ---------------------------------- Elasticsearch Exporter -----------------------------------
  - job_name: "elasticsearch-exporter"
    static_configs:
      - targets: ["esexporter:9114"]

  # ---------------------------------- Kafka Exporter -----------------------------------
  - job_name: "kafka_exporter"
    static_configs:
      - targets: ["kafkaexporter:9308"]

  # ---------------------------------- Kafka Minion -----------------------------------
  - job_name: "kafka_minion"
    static_configs:
      - targets: ["kafkaminion:8081"]
  # ---------------------------------- jmx Exporter -----------------------------------

  - job_name: "kafka"
    static_configs:
      - targets: ["10.90.26.8:7071", "10.90.26.9:7071", "10.90.26.10:7071"]  
      