# Global configuration
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# A list of scrape configurations.

# ---------------------------------- Node Exporter -----------------------------------

scrape_configs:
  - job_name: "self-node-exporter"
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "eslastic-node-exporter"
    static_configs:
      - targets: [ "es01:9100", "es02:9100", "es03:9100", "es04:9100", "es05:9100", "es06:9100", "es07:9100", "es08:9100", "es09:9100", "es01-m:9100", "es02-m:9100", "es03-m:9100" ]

  - job_name: "kafka-node-exporter"
    static_configs:
      - targets: ["kafka01:9093", "kafka02:9093", "kafka03:9093"]

  - job_name: "logstash-node-exporter"
    static_configs:
      - targets: ["logstash01:9100", "logstash02:9100", "logstash03:9100"]

  - job_name: "grafana-node-exporter"
    static_configs:
      - targets: ["grafana.tiptool.co:9100"]

  - job_name: "kibana-node-exporter"
    static_configs:
      - targets: ["kibana:9100"]      

  - job_name: "logger-node-exporter"
    static_configs:
      - targets: ["logger:9100"]

  - job_name: "gitlab-node-exporter"
    static_configs:
      - targets: ["gitlab:9100"]

# ---------------------------------- Elasticsearch Exporter -----------------------------------
  - job_name: "elasticsearch-exporter"
    static_configs:
      - targets: ["esexporter:9114"]

# ---------------------------------- Kafka Exporter -----------------------------------
  - job_name: "kafka_exporter"
    static_configs:
      - targets: ["kafkaexporter:9308"]