--- # ---------------------------------- Global Configs -----------------------------------
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "elasticsearch-rules.yaml"
  - "kafka-rules.yaml"

scrape_configs:
  # ---------------------------------- Node Exporter -----------------------------------
  - job_name: "node-exporter"
    static_configs:
      - targets: ["nodeexporter:9100"]
        labels:
          group: "self"

      - targets:
          [
            "es01:9100",
            "es02:9100",
            "es03:9100",
            "es04:9100",
            "es05:9100",
            "es06:9100",
            "es07:9100",
            "es08:9100",
            "es09:9100",
            "es01-m:9100",
            "es02-m:9100",
            "es03-m:9100",
          ]
        labels:
          group: "elasticsearch"

      - targets: ["kafka01:9100", "kafka02:9100", "kafka03:9100"]
        labels:
          group: "kafka"

      - targets: ["logstash01:9100", "logstash02:9100", "logstash03:9100"]
        labels:
          group: "logstash"

      - targets: ["grafana.tiptool.co:9100"]
        labels:
          group: "grafana"

      - targets: ["kibana:9100"]
        labels:
          group: "kibana"

      - targets: ["logger:9100"]
        labels:
          group: "logger"

      - targets: ["gitlab:9100"]
        labels:
          group: "gitlab"

  # ---------------------------------- Elasticsearch Exporter -----------------------------------
  - job_name: "elasticsearch-exporter"
    static_configs:
      - targets: ["esexporter:9114"]

  # ---------------------------------- Kafka Exporter -----------------------------------
  - job_name: "kafka_exporter"
    static_configs:
      - targets: ["kafkaexporter:9308"]
